name: casanu3va
favicon: null
layout_spectrum: 0.49729
typography_spectrum: 0.24639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050400'
    - '#9b9b99'
    - '#d74200'
    - '#722100'
    - '#d89400'
  brandStrength: 0.2716874876059592
  lightness: 0.4626862849108875
  saturation: 0.14109694166108966
  rhythmicContrast: 0.8495297376066446
purpose: []
